"""Remove certificate_path from test_session

Revision ID: 321d4ec87900
Revises: cc0272b4360b
Create Date: 2025-11-09 17:17:33.965239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321d4ec87900'
down_revision = 'cc0272b4360b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_sessions', 'certificate_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_sessions', sa.Column('certificate_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

