"""Add new_field

Revision ID: cc0272b4360b
Revises: 001
Create Date: 2025-11-09 17:15:39.073885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc0272b4360b'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_results_id', table_name='test_results')
    op.drop_table('test_results')
    op.add_column('test_sessions', sa.Column('certificate_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_sessions', 'certificate_path')
    op.create_table('test_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('correct_answers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score_percentage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name='test_results_material_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='test_results_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='test_results_pkey')
    )
    op.create_index('ix_test_results_id', 'test_results', ['id'], unique=False)
    # ### end Alembic commands ###

